### ISSUE TITLE
OP.GG is dead

### ISSUE THREAD

**Issue by ve1mi** [Soundofdarkness/RuneBook#107]

**Comment by HannoMartinus** [comment]
![image](https://user-images.githubusercontent.com/84947849/153697468-bf153c0f-a0a8-4c04-bb17-98f441d681b6.png)
Same thing here.

**Comment by Soundofdarkness** [comment]
Yup, noticed it too, I will look into it in the coming days.

**Comment by Soundofdarkness** [comment]
It seems so far that op.gg switched to using random and (presumably ?) changing css selectors now, so I'm not quite sure yet if there is a way to get the plugin to work again.

**Comment by 11Tuvork28** [comment]
Not dead anymore I got a PR on the way.
Looks like the plugin got a whole lot easier because they store all the data in a json object which we just need to extract from the html and then we can even use other stuff from them like items or counter pick

**Comment by ve1mi** [comment]
> Not dead anymore I got a PR on the way. Looks like the plugin got a whole lot easier because they store all the data in a json object which we just need to extract from the html and then we can even use other stuff from them like items or counter pick

Super info, I will wait the next update
