### ISSUE TITLE
Item set Exporter doesn't detect custom LoL directory.

### ISSUE THREAD

**Issue by HannoMartinus** [Soundofdarkness/RuneBook#111]
Took me quite some time to figure it out.
Runebook itself detects my custom LoL installation directory (`D:\Riot Games...`), but the new Item set Exporter feature doesn't and just drops the files by default in `C:\Riot Games\League of Legends\Config\Champions`
![image](https://user-images.githubusercontent.com/84947849/154227983-852a8a19-bf48-424a-882c-c23b1e0802f5.png)

**Comment by Soundofdarkness** [comment]
Thanks for the report ! 
I'm going to take a look on that and hopefully fix it soon.

**Comment by HannoMartinus** [comment]
The league install I had was from 2019, so I ended up reinstalling both LoL and Runebook which fixed the problem. I couldn't replicate this problem in VM so I think the cause is probably something wrong with my LoL game files or my own install of Runebook rather than a bug in the code.
