### ISSUE TITLE
Not sure where to ask beginner questions, can't get Runebook to work on Mac

### ISSUE THREAD

**Issue by Kestoon** [Soundofdarkness/RuneBook#112]
Hello,
Sorry if this is not the right place to ask, I have looked everywhere I could. found nothing on reddit etc.
Anyway I guess everything is in the title. Today, I uninstalled the old version of Runebook that I had on my (2014) MacbookPro as I wasn't loading any pages from op.gg. 
I am trying to reinstall it, but I cannot make it work. I tried downloading all different versions of the latest release but wasn't sure which was the one. Do you have any Mac users ? 
Any help would be appreciated

**Comment by Soundofdarkness** [comment]
Unfortunately we aren't currently building for macOS so the only way atm would be to build it from source. 
I can try to help if you want to do that, but since I dont have a macOS machine available atm, I'm not sure how much I can help.

**Comment by Soundofdarkness** [comment]
No problem ! I'm going to close the issue for now, but just reopen it whenever you feel like trying.
