### ISSUE TITLE
BLITZ.GG not working

### ISSUE THREAD

**Issue by HannoMartinus** [Soundofdarkness/RuneBook#120]
As of 20/04, blitz.gg stopped working on version 1.15.0

**Status Update** (25/05/2022):
BLITZ.GG: Down ❌
Lolalytics: Down ❌
OP.GG: Down ❌
U.GG: Working ✅
METAsrc: Down ❌

**Comment by 11Tuvork28** [comment]
Hi, thanks for reporting this👍
Currently I can't look into it but I will fix it as soon as I have time again.
Does it happen on every champion or just Malzahar?

**Comment by Soundofdarkness** [comment]
I personally have nearly no knowledge of graphql either, but im going to take a look if I have time too. (I will mention it here if im working on it so we don't end up with two people fixing the same)

**Comment by Soundofdarkness** [comment]
Yup, going to take a look at the PR's soon, and I'm not sure, should we just try to revert the last PR for the time being and re-add it later on ? (at least in case we don't find any obvious cause soon)

**Comment by 11Tuvork28** [comment]
I have a better idea:
We make a dev branch from current master and rebase master onto 0edd00f  and merge current PRs.
That way we can experiment with it and in the mean time release a new version so that the program is in a more useable state.
What do you think?

**Comment by Soundofdarkness** [comment]
Yup, sounds good, going to work on doing that tomorrow (since i think i have to do it, but not sure)

**Comment by 11Tuvork28** [comment]
Sure, or if big if you feel I can be trusted add me as a collaborator and I can do that. Wow I feel bad for bringing this up anyway thanks for your quick response time

**Comment by Soundofdarkness** [comment]
Don't worry, I will for now still see to that, but that is something I'm debating anyways if I'm continuing to not be able to do anything to help (as in, moving the project into a community, and giving 1-3 people trusted access as maintainers after a vote if they want and with me just being there in case I have time for once)
