### ISSUE TITLE
Scrollbar does not work as expected

### ISSUE THREAD

**Issue by Rerago** [Soundofdarkness/RuneBook#127]
If there are too many rune pages, the scrollbar does not appear within the plugin page but on the whole application. We should fix that :)

![image](https://user-images.githubusercontent.com/65850767/187086206-dfd422c8-5f8e-4297-ae56-0f696bac1f85.png)

@11Tuvork28 That shouldn't be a problem for you, should it?

**Comment by 11Tuvork28** [comment]
In general not buuuuut I have limited time and to much on my hands. Will see but I don't know why its broken in the first place, need to investigate that

**Comment by Soundofdarkness** [comment]
This should be fixed now, so I'm going to close this.
In case something isn't fixed yet, feel free to reopen it !
