### ISSUE TITLE
Single File Release

### ISSUE THREAD

**Issue by Rerago** [Soundofdarkness/RuneBook#15]
The OrangeNote version also offered a version without setup. I preferred this version over a setup. Can we do the same?

https://github.com/OrangeNote/RuneBook/releases

That is btw. the reason why I changed the build settings back :D

**Comment by Soundofdarkness** [comment]
Oh okay, yeah I can definitely look into that ^^

**Comment by Soundofdarkness** [comment]
Yup, just checked, I can add that again in a few minutes.

**Comment by Soundofdarkness** [comment]
Okay, single file release is added back in the latest version 😄

**Comment by TinyRaindrop** [comment]
How does single file work exactly?

**Comment by Soundofdarkness** [comment]
I think its just unpacking the whole app on runtime into ram, without installing anything aside from the usual %appdata%/Runebook settings directory.
But not 100% sure about the internals of electron-builder and electron itself.
