### ISSUE TITLE
Dark-Theme Settings

### ISSUE THREAD

**Issue by Rerago** [Soundofdarkness/RuneBook#17]
In the Dark Theme the settings are still very bright. That hits you a bit. There is also an old issue about it:

https://github.com/OrangeNote/RuneBook/issues/72

So if there is someone who likes CSS. Here is something for you.

![darksettings](https://user-images.githubusercontent.com/65850767/83072156-8ff0ef80-a06e-11ea-8b8f-897ae9a1bb8c.png)

**Comment by Rerago** [comment]
I found something.

https://github.com/Dancanplay/RuneBook/commit/53cccf8c79965f1ec85e85b01b10ed63c7819597

Doesn't work 100% and could still use some improvements (e.g. text-color between the separators). But in itself a good start.

**Comment by Soundofdarkness** [comment]
Fixed in current master, so I'm going to close this, thanks for all the good commits 👍
