### ISSUE TITLE
Different Runebook forks

### ISSUE THREAD

**Issue by Rerago** [Soundofdarkness/RuneBook#2]
Hello, everyone,

currently there are roughly 4 current Runebook forks. Wouldn't we rather limit ourselves to an active one and work together?

@lowyiyiu
@TinyRaindrop
@Pwn2OwnLive
@Soundofdarkness

What do you think? I'm gonna go ahead and contribute to this one.

**Comment by TinyRaindrop** [comment]
Hi!
So after the version thing broke I looked around for a working app and decided to fix it myself. Afterwards, I looked better and found that other people also continue the development, which is awesome.

There's also @DanielOrtez

I'd prefer if we all worked together on one project.

**Comment by Soundofdarkness** [comment]
Hey :) 
Generally, exactly the same happened for me. It broke, I saw that it wasn't maintained anymore, and forked it.

But I fully agree to just have one fork running and all help on that one. Im open to help on whatever version/fork is wanted :)

**Comment by TinyRaindrop** [comment]
This repo seems to be [the first working fork](https://github.com/Soundofdarkness/RuneBook/releases/tag/v1.8.14), it also has astounding **seven** people who starred the project (insane popularity), so I guess we could pour in here.

**Comment by Soundofdarkness** [comment]
Well, that certainly works then :)
I'd say we can just wait a day or two if the maintainers of the two other forks chime in as well and then we could start updating things. 
(And I should probably start on properly setting up the repository after that)

**Comment by DanielOrtez** [comment]
I think that's a great idea. What would be the main repository?

**Comment by TinyRaindrop** [comment]
I suggest we keep this one, seems like a good ground.

**Comment by Pwn2OwnLive** [comment]
Hello all,

I would be glad to contribute to this project. I forked the repo when I saw
that Runebook wasn't working
since I save a lot of local rune pages to switch to and it was a good
opportunity to support my stream. :)

**Comment by Soundofdarkness** [comment]
Okay nice to hear that :) 
Generally I'm very happy if we use this repository (*might be biased*), but im absolutely open to helping on a different one if we see that as useful.

**Comment by Rerago** [comment]
@OrangeNote will certainly also be happy that his baby may have a new home^^

**Comment by Pwn2OwnLive** [comment]
I have sent an email to Jakob Abfalter (jakobabfalter@gmail.com) at
*Koreanbuilds.net* and below is his response:

Hello,
>


Thanks for the interest. We offer bulk files containing all build data in
> JSON format, which are updated daily. This would be the preferred solution
> because then I don't have to (necessarily) keep my API Interface stable and
> can minimize API load.
>


You can download it like this:
>


https://statics.koreanbuilds.net/bulk/latest.tar.gz
>


this will always give you builds from the latest patch (right now 10.10)
>


https://statics.koreanbuilds.net/bulk/last.tar.gz
>


will always give you from the previous patch. (right now 10.9)
>


You can also retrieve data for a specific patch like this:
>


https://statics.koreanbuilds.net/bulk/v10-8.tar.gz
>


If you have any questions, please let me know.
>


Best,
> Jakob

**Comment by lowyiyiu** [comment]
I forked the project not knowing there're active forks out there (only checked a few of the forks on random and didn't find any work done) but it will be nice to have everyone contributing on the same fork.

So far what I've done for mine are:
- fix ddragon version
- fix u.gg
- added op.gg urf

I've also disable some features that I'm not using (autoupdater).

**Comment by Pwn2OwnLive** [comment]
Hello all. When will we get an invite as contributors?

**Comment by TinyRaindrop** [comment]
> 
> Hello all. When will we get an invite as contributors?

Current setup allows you to fork this repo, commit changes to your own fork, and then create a pull request to merge your commits to this one.

**Comment by TinyRaindrop** [comment]
@yodarunamok we have some stuff going here, care to join?

**Comment by OrangeNote** [comment]
> @OrangeNote will certainly also be happy that his baby may have a new home^^

Hey guys, thanks for still believing in the project! Of course I'm happy to see that the community is still involved in the maintenance of RuneBook.

Currently I'm not interested in developing, fixing or giving any kind of help with the codebase. So I wish you good luck and I hope the app can still serve all the users that originally supported my idea.

Even if it's not mandatory, thanks for keeping the original list of acknowledgements. Of course you can extend it with any other mention you'll find worth including.

✌️

**Comment by yodarunamok** [comment]
I suppose I'm game.

An item related to that though: in addition to free downloads, I was planning on also making the (updated) Mac version available from the Mac App Store and charging $5. There are a few reasons for this:

- Apple charges $99/yr for the privilege of putting an app there, plus 30% of sales 😳
- Convenience (people can download the thing for free, so they can tip me for going to the trouble of making installation easier)
- Help support my other projects.

Of course the app store listing would indicate that RuneBook could be downloaded for free elsewhere (among other things.)

Please let me know if all y'all have a problem with this.

**Comment by yodarunamok** [comment]
@Soundofdarkness I totally understand, and I'm happy to just go with my own fork. That said, I'd like to respond to your points:

1. I don't think there would need to be changes to anything in the repository, and if so, they would still go through the PR process. I've never tried to get an app approved for an app store so I'm stepping into uncharted territory there.
2. True enough, though it may be that enough value would be created by making installation and use more convenient. I've asked Riot about this as I'd have to deal with it regardless of where it was done.
3. Partly true. There is certainly plenty of value for the app itself, however the point of charging is to recoup costs associated with the Mac App Store specifically. The $99/yr cost would be borne by a single individual (as on the app store it would be associated with a single individual's developer account.) With the availability of an identical free version, it is possible that the app would lose money some years on the app store. I really have no idea.

**Comment by Soundofdarkness** [comment]
@yodarunamok Generally speaking, asking Riot is probably the best idea for now, and when you got a response we can think more about this. But to answer to the points:

1. Absolutely. What I meant was rather that if something in the app version doesn't work, Users will most likely come to this repository (after noticing that the original one is archieved), and will file issues here, while I don't have control over what happens in that version.

2. Sounds good to ask them 😄 

3. I do understand why you want to add a fee to it, don't worry. And just to mention that much, I personally do not want to make any profit of this app, especially not since I didn't even create it in the first place.

And I just have a few things to add
- You should probably look up if apple even still accepts electron apps in their Appstore, since if I remember correctly, they had a few issues with them at some point.
- As I've mentioned in the first [release](https://github.com/Soundofdarkness/RuneBook/releases/tag/v1.8.12) after maintainer switch, I'm still working on fixing the build for macOS, so you should probably expect that that's still going to happen since I finally got my hands on an older MacBook to test it there again (and I'm still working on adding a general CI to this, which supports building for macOS).

But aside from that, let's just see about Riot's stance on this.

**Comment by TinyRaindrop** [comment]
@Soundofdarkness 
> Users will most likely come to this repository 
pretty sure that no one knows about this repo, we have to prepare a Reddit Press release.

**Comment by Soundofdarkness** [comment]
@TinyRaindrop That too, but if they search for a Repository, they will probably land on this one after the one from OrangeNote.

**Comment by Peptino** [comment]
It's great that you maintain runebook as I use it every day! Thanks to all of you :)

Maybe Orangenote can add a link to this fork. I don't know whether this is possible when it's already archived.

**Comment by OrangeNote** [comment]
> Maybe Orangenote can add a link to this fork. I don't know whether this is possible when it's already archived.

I guess I could. Just mention me when this fork will be in good shape and ready to be publicized.

**Comment by Rerago** [comment]
@OrangeNote 
I would claim currently the forke is in a very good condition :)

**Comment by OrangeNote** [comment]
Sure! I've added a line at the top of the original readme file, linking to this fork and its contributors.

**Comment by Rerago** [comment]
Thanks @OrangeNote :)

@all
i think the issue can be closed now too^^

**Comment by Soundofdarkness** [comment]
Sweet, thanks !
