### ISSUE TITLE
yarn?!

### ISSUE THREAD

**Issue by Rerago** [Soundofdarkness/RuneBook#31]
Did we even need yarn? I mean, it's out of sync all the time, and everybody uses npm tbh^^

**Comment by TinyRaindrop** [comment]
Yarn works fine for me, it ensures everyone has the same versions of packages installed. Plus it's a bit faster.

npm used to be a pain in the ass until they added `npm ci` that's basically equal to `yarn install` and reads from lockfile. So there's not much difference in what to use, we can switch to npm if you really want to.

**Comment by Soundofdarkness** [comment]
I personally currently use the old yarn, since it's indentical to npm, just a bit faster. 
For development you can still use npm, you just have separate lockfiles, which sometimes means that you have a slightly different version

**Comment by Soundofdarkness** [comment]
And it's important to mention that yarn allows to override package versions from dependencies, which is sadly necessary sometimes

**Comment by Rerago** [comment]
I don't care about the principle. I only have NPM in VS Code and VS itself takes NPM as default. I didn't even know yarn until then (since javascript is not my language, usually)

So we can keep it.

**Comment by Soundofdarkness** [comment]
Both work absolutely fine, and should work together for the most part. (And I think the userbase is pretty much equally split too :^) ). Only point that matters is that the release build uses the same manager for consistency.
