### ISSUE TITLE
Small Heads-up

### ISSUE THREAD

**Issue by Soundofdarkness** [Soundofdarkness/RuneBook#36]
Hey, just wanted to give a small heads up: I will be a bit busy for the next few days, so if I'm not reacting or doing much, please don't worry, I will be back to being able to do more in around a week, and will go trough all the PR's and test everything + hopefully finally get around to actually add a code of conduct, etc.

Sorry

**Comment by Rerago** [comment]
@Soundofdarkness
I think you can close the issue ;)

**Comment by Soundofdarkness** [comment]
I guess I will yep, but might open something similar again since the general problem still continues (and will continue for probably years).
