### ISSUE TITLE
Darktheme Choosing

### ISSUE THREAD

**Issue by Soundofdarkness** [Soundofdarkness/RuneBook#39]
First of all, thank you guys for both PR's about the settings page.
Okay, now we have the problem that we have two independent PR's implementing the dark theme for settings. Im personally not really sure which one to take, since im pretty bad at using css (maybe because im mostly working on backend stuff ...).
But yeah, im just opening this issue if you guys know which one is the best one to take.

**Comment by TinyRaindrop** [comment]
### Comparison
#29 
![Greenshot 2020-06-09_21-07-24](https://user-images.githubusercontent.com/48414047/84184000-5029ff00-aa95-11ea-819d-1e8561232d5d.png)

#33 
![Greenshot 2020-06-09_21-05-07](https://user-images.githubusercontent.com/48414047/84184001-515b2c00-aa95-11ea-90c2-fbc2ba51f432.png)

I say we merge #29 as it's more thoroughly done, and kindly ask @Pwn2OwnLive to resubmit Greek translation.
This would fix dark settings in timely manner, and I can start [merging](https://github.com/Soundofdarkness/RuneBook/pull/27#issuecomment-637575748) dark.css and light.css into one and cleaning up.

**Comment by TinyRaindrop** [comment]
#27 looks fine. We could merge it and cherry-pick [this commit](https://github.com/Soundofdarkness/RuneBook/pull/29/commits/754009e0a5c2a462e6b3e2b72065edff141fcdad) from #29, let's decide and move on.

**Comment by Rerago** [comment]
If so, i would also cherry pick [this](https://github.com/Soundofdarkness/RuneBook/pull/29/commits/412cdb6210a8fc003646cacb55b1d519deeaa3c6). Because the language selection does not work in the current master. You would see if you would rebase.

I still think the drop-shadown is too bright. And I also still think that we need to keep the two CSS files on the same level.

But ok lets merge #27. But we should think about this:

https://dev.to/ananyaneogi/create-a-dark-light-mode-switch-with-css-variables-34l8

Because two different CSS files that are not completely identical except for the property make it difficult to maintain the file.

**Comment by TinyRaindrop** [comment]
>  And I also still think that we need to keep the two CSS files on the same level.
I will extract colors into separate theme files and we'll be left with a single main.css, so it doesn't matter. Already mentioned it somewhere.

**Comment by Rerago** [comment]
Can we please still use the following background shade?

```
.ui.inverted.dimmer {
	background-color: rgba(64,64,64,.85);
}
```

**Comment by Soundofdarkness** [comment]
Let me check it, but sure, I just still need to get the changes from your now closed PR.

(just not that used to cherry-picks and the likes, so im pretty slow at that)

**Comment by Soundofdarkness** [comment]
Yup, that background shade seems better. Going to commit that with the dropdown fix, since I can't seem to get access to the PR which had it.

**Comment by Soundofdarkness** [comment]
Okay, added everything. Now we can test if the current master works correctly and then im going to merge the rest after they work with the current theme.

**Comment by Rerago** [comment]
Not quite you have forgotten the following commit:

https://github.com/Soundofdarkness/RuneBook/pull/29/commits/754009e0a5c2a462e6b3e2b72065edff141fcdad

I've prepared a PR for it.

**Comment by Soundofdarkness** [comment]
Perfect thanks, I couldn't add that one before due to not getting commits from closed PR's. Going to merge that in a few minutes
