### ISSUE TITLE
Missing rune images

### ISSUE THREAD

**Issue by Rerago** [Soundofdarkness/RuneBook#4]
I have a problem, which is probably due to my surroundings.

The pictures are not displayed correctly. @lowyiyiu has fixed this problem in his version. In which he added the following:

`<div style="display:flex;align-items:center">`

Now I wonder if there might be a solution with "semantic-ui-css" (which is used here). I'm just quite new to javascript/web development. I usually work more in the backend.

![missing images](https://user-images.githubusercontent.com/65850767/82754013-6fa10680-9dca-11ea-8298-81df0993fec8.png)

**Comment by TinyRaindrop** [comment]
you could keep semantic-ui-css@2.2.14

**Comment by Rerago** [comment]
I have the problem even without changing versions.

I think it has something to do with my environment. But with the above mentioned change it works.

For example, I have no Chrome installed but only Edge.

**Comment by TinyRaindrop** [comment]
You don't need to have anything but Node.js installed. 

package.json specifies versions for dependencies, it's "^2.2.14" for semantic-ui. So it's updated to the last minor version - 2.4.2, which breaks the images.

Change to "~2.2.14" or "~2.3.0", then run **npm install** again.

**Comment by Rerago** [comment]
On my client the images are also broken under v2.2.14. Even @lowyiyiu (who made the above mentioned adjustment) still uses v2.2.14.

So I guess we have the same problem

**Comment by TinyRaindrop** [comment]
Go into node_modules/semantic-ui and check version. It's 2.4.2 because of what i said above

about package.json versioning: https://semver.npmjs.com/

**Comment by Rerago** [comment]
Ahhh ok got it^^

But still I think we should fix the problem rather than stay on an old version.

**Comment by Soundofdarkness** [comment]
Interestingly enough this doesnt happen to me, but i wonder if yarn's version resolution works differently than the one of npm, which maybe uses a version that still works. Probably have to test this later/tomorrow too, since im sadly pretty busy today

**Comment by TinyRaindrop** [comment]
New version probably uses different class names, shouldn't be too hard to fix

**Comment by TinyRaindrop** [comment]
Let's all agree not to mess with dependencies without a good reason. Not everything needs to be updated.

All that needed to be done in this case was to look what version of the package is used in the original repo - [yarn.lock](https://github.com/OrangeNote/RuneBook/blob/master/yarn.lock) provides this information: 

semantic-ui-css@^2.2.14:
  version **"2.3.1"**

Thus, in package.json specify this exact version, and don't update to 2.4.2.

**Comment by Rerago** [comment]
Ok du hast mich^^. Habe #3 entsprechend angepasst (das mit einer fixen semantic-ui-cs version gearbeitet wird) und #5 geschlossen. Wir sollte das problem noch mal angehen wenn wir semantic-ui-cs updaten.
