### ISSUE TITLE
Dealing with new language strings

### ISSUE THREAD

**Issue by TinyRaindrop** [Soundofdarkness/RuneBook#47]
If a locale is missing the requested string, riot-i18n doesn't check the default language (en) for the same string, and displays the key instead, e.g. "settings.favautoupload". It can be [easily fixed](https://github.com/TinyRaindrop/riot-i18n/commit/89aebec3cdefe2a1c31a475693aafd96818fb6f5), so that any missing string is taken from en.json by default.

Works just fine, the locale in this example doesn't have the 'autoupload' string, and the text is taken from en.json.
<img src="https://i.imgur.com/tfNBXm6.png" width=60%>

But riot-i18n module isn't updated anymore, and changing the dependency to `riot-i18n: "github:TinyRaindrop/riot-i18n#master"` is a bit extreme. 

So, when adding new lang strings, should we just copy them to every locale, untranslated?

**Comment by Soundofdarkness** [comment]
I guess for now we just copy them untranslated, but yes, later on we should move to something like the version your repo has.

**Comment by TinyRaindrop** [comment]
Of course, you're right; I must've had a heat stroke. We need to keep all strings in locale files so that translators would see what is left untranslated.

**Comment by Soundofdarkness** [comment]
Nah, all good, generally your idea is in my opinion not bad at all 😄

**Comment by Rerago** [comment]
In principle, the string must be included in every file. To make the work easier for the translators.

But still we should replace "riot-i18n" times. Since this is the reason why we can't update riot.js :D

**Comment by TinyRaindrop** [comment]
> But still we should replace "riot-i18n" 

Adopt this abandoned module in npm?

**Comment by Rerago** [comment]
What? I mean that "riot" is currently at version 4.13.2 But we are stuck on 3.13.2 because "riot-i18n" (which is not from the same developers and hasn't been developed for 3 years) doesn't work with a higher version.

So I think we should switch to some other module. Which one exactly? I don't know, something small that is still being actively developed.
