### ISSUE TITLE
Linux build?

### ISSUE THREAD

**Issue by Eated-Universe** [Soundofdarkness/RuneBook#67]
Hello! Thank you very much for reviving this project and updating it!
I wish you good luck in improving it and maintaining it.
I have a request, if it is possible....I am playing LoL on Linux, and you are not building version for it. Not surprisingly as League of legends is supported for MacOS and Win only, but still.... there are player who use Wine with Linux...not many but t we exist lol
As this app is electron based, it shouldn't be too hard for you to add Linux build.
Even I- managed to forked repo, and even tough I am very dumb for these things, somehow managed with copy/pasting stuff from search results to make it compile unpacked and app-image version.
And it worked :D
But I spent hours doing that :(
So if it is not too hard, it would be AWESOME of you to add a Linux build.
In any case, thank you for keeping this project alive! cheers

**Comment by VileoSufora** [comment]
Would you mind uploading that as a fork? I've been looking for this too, especially with Blitz not working on Linux right now.

**Comment by Eated-Universe** [comment]
I did, like I said in the post above. It's on my GitHub, check there.
But be warned, I am not electron dev or any dev at all, so I take no responsibility. I just added/eddited few lines to make it compile Linux version.
But it does work for me, so you can try it (do tell me if it works fine...it should)

https://github.com/Eated-Universe/RuneBook/releases/tag/v1.11.3_linux

**Comment by VileoSufora** [comment]
Oh, sorry, I misinterpreted what you meant, then.
I tried out the AppImage version and it works perfectly on Mint 19.3! Thanks!

**Comment by Eated-Universe** [comment]
I am glad I helped another idiot like myself who plays on Linux lol. Good luck

**Comment by Rerago** [comment]
@Soundofdarkness I have no idea, but is it possible to create the Linux binary under Windows?

**Comment by Soundofdarkness** [comment]
I can probably try to build it on WSL for the next release, but I guess that's about it.
I'm already more than surprised that it even works on Linux, considering it has to connect to a wine/proton(?) container and read files inside it too.

**Comment by Eated-Universe** [comment]
The app itself is a electron based, and it support linux, mac and windows natively. Basically I only needed to add the following:
`    "distlin": "electron-builder --linux",`

and change dist:all to include Linux:
`    "dist:all": "electron-builder -mwl -p onTagOrDraft"`

and then install dependencies and run

npm run distlin

System tray option wont work, as the code is meant for Mac and Windows. You could probably add it for Linux too, but I do not know how it is done.
As you can compile Mac version on Windows, you can Linux on Windows and vice versa. Linux can compile Mac and Windows too.

Testing it would probably be best in native environment. I compiled newest version (with u.gg fix and system tray) and all works besides error about system tray icon and the option for minimize to SysTray wont work like I mentioned.

I fiddled with main.js to edit the lines for it and make it work in Linux, but I do not posses sufficient knowledge, and already I struggled to find how to add lines to package.json to compile it for Linux.

RuneBook does not make any connection to wine/proton besides reading necessary files from LoL and those files are not platform specific (json files i think) so making it works is basically compiling a unpacked binary or AppImage or Snap and then pointing it manually to League .exe as it wont auto detect it.

**Comment by Soundofdarkness** [comment]
Aight,
I'm very well aware that electron (and most of Runebooks code for that matter) works cross-platform. 
What I meant in terms of being surprised is that I didn't expect it to be able to connect to the league client http/ws api if its running in wine/proton.

System tray is something I might be able to try and add for linux at some point, but not for the time being. 
And yes, electron builder is able to build for linux using a public service, not by itself. And I'm usually trying to build the things myself to at least have some control over them. Which is why I will try to build in WSL. 

Testing would certainly best be done natively, but that's nothing I'm able to do since I will not install linux on a desktop just to test Runebook. And none of my current Linux installs have GPU's or desktop environments for that matter.

So in the end I will try to provide a linux build and that probably all.
If there are any linux specific errors I will not really be able to do anything unless its a simple fix, since I can't test it.

**Comment by Eated-Universe** [comment]
System tray (to me personally) is the least relevant feature in RuneBook, so it might as well not exist, but I'd welcome it if it comes at any time.

I would be extremely grateful (and I believe there will be some other Linux users at least) for a official Linux build from someone who actually know what the hell is he doing and not me fiddling with thing I understand superficially at best :) So take your time and do things how you wish/want.

I'd be more then willing to test and provide any inputs on errors or possible fixes that I can. 

I consider this "issue" closed. Feel free to reopen it for any reason if needed, and cheers

**Comment by Soundofdarkness** [comment]
@Eated-Universe Linux build is uploaded now, if its not working let me know (will try rebuilding on linux and not WSL then)
Glhf !

**Comment by Eated-Universe** [comment]
@Soundofdarkness 
First of all. Thank you 👍
Second, I have tested AppImage and the binary. They both work properly, as far as I've tested them- custom  game, and testing few champs from few sources.
There is an error at startup of the app regarding the minimizing to tray code, and feature itself being broken and if you turn it on in settings, it minimizes the app (to void) and it stays in memory but cannot be recalled as there is no way to call it back.
This is the error at the startup (if it helps on fixing the feature at some point down the line).
![Screenshot_20210109_193242](https://user-images.githubusercontent.com/50053477/104105938-25fe2100-52b2-11eb-9d11-4f5789a3ba43.png)
cheers!

**Comment by Soundofdarkness** [comment]
Ah okay, good to know, gonna try if I can just add a simple platform check and otherwise dont load the tray icon tomorrow, but thanks for reporting ^^

**Comment by Soundofdarkness** [comment]
Okay, I did publish a fix for the problem and well, I hope it works, since I have no idea.
I'm going to close this for the time being, but if its still not fixed feel free to reopen this.

**Comment by Eated-Universe** [comment]
@Soundofdarkness No error at startup and everything seems to be working.
Thank for doing this!
Great job  👍

**Comment by Soundofdarkness** [comment]
Perfect, and no problem ! If its working that easily then its absolutely worth doing 👍 
Glhf !
