### ISSUE TITLE
nsis error 1.14.1

### ISSUE THREAD

**Issue by ve1mi** [Soundofdarkness/RuneBook#81]
1.14.1.exe
![2021-05-24_14-08-45](https://user-images.githubusercontent.com/45261656/119339373-bf463680-bc99-11eb-9050-55719faa7f80.png)

**Comment by Soundofdarkness** [comment]
Hmm, interesting, no idea how that happened, but im going to take a look when im back on my pc later today.
Sorry for the inconvenience, I will try to fix it asap.
(I feel like I just need to reupload it and it will work, but we will see ..)

**Comment by ve1mi** [comment]
nice, thx dev

**Comment by Soundofdarkness** [comment]
No problem, should be fixed now, seemed like electron-builder just didn't completely upload it.
I'm going to close this for now, but am pinning it still in case the linux version is bugged too,
but in any case, if there are further issues, just reopen the issue or make a new one.
Thanks for the report and apologies for the delay !
