### ISSUE TITLE
Rune pages arent exported 1.14.1

### ISSUE THREAD

**Issue by ve1mi** [Soundofdarkness/RuneBook#84]
1.14.0 working fine. Runes page from sources isnt exported (opgg ugg and etc). Old local pages are exported - this okay 

![2021-05-25_01-24-15](https://user-images.githubusercontent.com/45261656/119414614-8a1d0100-bcf8-11eb-8e96-4aa972eaeee3.png)
![2021-05-25_01-23-14](https://user-images.githubusercontent.com/45261656/119414617-8ab59780-bcf8-11eb-8edb-6936aa06babc.png)
![2021-05-25_01-32-06](https://user-images.githubusercontent.com/45261656/119414839-0adbfd00-bcf9-11eb-99d3-e0abf47ecea2.png)

**Comment by mugiritsu** [comment]
Same issue here. The LoL Client says there was a problem with the runes with a red danger symbol. Then I have to edit manually the runes and set the secondary rune tree by hand.

**Comment by Rerago** [comment]
@mugiritsu this should be fixed with #85

**Comment by Soundofdarkness** [comment]
Can confirm, going to merge soon, see first comment on the newest issue

**Comment by Soundofdarkness** [comment]
Should be all fixed with 1.14.2 now.
Going to close this for now, but in any case, if there are issues, just reopen this issue or create a new one !
Thanks for the fix @Rerago
