### ISSUE TITLE
Rune export still doesn't work 1.14.2.exe

### ISSUE THREAD

**Issue by ve1mi** [Soundofdarkness/RuneBook#87]
![2021-05-26_22-45-44](https://user-images.githubusercontent.com/45261656/119721808-3e8f6200-be74-11eb-8a56-0aedfcde0d7e.png)

**Comment by Soundofdarkness** [comment]
You just need to create a new runepage (or select a different one in c-select), since the current active one is one of the default ones from all I can tell, and they cant be modified

**Comment by ve1mi** [comment]
Thanks working :)
