### ISSUE TITLE
u.gg is a little broken

### ISSUE THREAD

**Issue by ve1mi** [Soundofdarkness/RuneBook#88]
![2021-05-27_23-04-08](https://user-images.githubusercontent.com/45261656/119890099-11a88100-bf40-11eb-8120-4642c6241c9a.png)

**Comment by Soundofdarkness** [comment]
Hey,
sorry for the delay, I will try to look into this in the coming days,
but I cant guarantee a quick fix since I'm pretty busy.
So far it seems to me like its just a matter of sorting u.gg's rune response since thats the only plugin with this problem.

**Comment by Soundofdarkness** [comment]
Alright, current master should include a fix (but I'm not exactly happy with the quality of said piece of code).
I'm going to wait a few days in case somebody finds an obvious flaw with it that I might have missed in my testing,
but after that I'm going to publish it.

**Comment by ve1mi** [comment]
thanks, was busy these days)

**Comment by Soundofdarkness** [comment]
Yup, sounds very familiar !
I hope it works like that, if you don't want to wait, you can just run it from source,
and of course, in case there are any issues, just post them here or in a new issue !
(will try to fix them, but yeah, same case with being busy still applies sadly >.>)

**Comment by Rerago** [comment]
I have submitted a fix. It should fix the problem.
