### ISSUE TITLE
rework runes.lol

### ISSUE THREAD

**Issue by Rerago** [Soundofdarkness/RuneBook#9]
runes.lol only works halfway (some runes are not taken over correctly).

You can see the whole thing very well when you use "Shen".

I think in the end we could rewrite the plugin since they only redirect to "lolalytics" anyway. And they actually use a nice json interface.

**Comment by TinyRaindrop** [comment]
Runes.lol is lolalytics now, so the task is to create a brand new plugin for lolalytics

**Comment by Soundofdarkness** [comment]
Yup, seems like they have some kind of api too, but not sure if its usable
Example ([Kayle](https://api.op.lol/champion/2/?patch=10.10&cid=10&lane=default&tier=platinum_plus&queue=420&region=all))

**Comment by Rerago** [comment]
I'm almost done with LoLalytics. So wait another 1 or 2 hours and we can include it in the v1.10.0 release.

**Comment by Rerago** [comment]
Anyone have any idea how their rune data works? ^^

**Comment by Rerago** [comment]
Okay, I figured it out. They calculate the pick and win rate for every single rune. Then they calculate the respective Key-Stone and on this basis they calculate the rune list for "most picked" and "highest win rate".

You can have a look at the code in their Java-Script. But honestly I don't want to take the code 1:1 without their permission.

Does anyone have Facebook/Twitter/Reddit or something to write to them?

If not, I would have to rewrite the code my way. I understand now how it works. But I don't want to steal the code.

**Comment by TinyRaindrop** [comment]
They only have [discord](https://discord.gg/zKyaZ6w) as far as i'm aware.

**Comment by Rerago** [comment]
Some one wanna ask them? I can join but thats all^^

**Comment by TinyRaindrop** [comment]
I haven't seen actual developers there, but I'll ask around.

**Comment by TinyRaindrop** [comment]
@Rerago, developer of lolalytics and op.lol is Grievous#4799 on discord

https://discord.gg/zKyaZ6w

![18_21-#lolalytics-specific](https://user-images.githubusercontent.com/48414047/83538073-13429300-a4fe-11ea-8aea-da968e2b90ab.png)
![18_17-#lolalytics-specific](https://user-images.githubusercontent.com/48414047/83538070-12116600-a4fe-11ea-8028-0e9c00802ea6.png)

**Comment by Rerago** [comment]
Send him a link to this issue here. We "only" need the runes. lolalytics can do much more. Maybe it will be faster :)

**Comment by Soundofdarkness** [comment]
Closed, thanks for the PR !
